Repository connect-foundation/2019-10, pull requests merged in 2019-12, with the labels that each got.

#115 Logger 구현
  packages/server/package-lock.json
  packages/server/package.json
  packages/server/src/logger/index.ts
Labels: enhancement

#116 entity 와 migration 수정 및 동기화
  packages/typeorm/.env.dummy
  packages/typeorm/src/apply-migration/.keep
  packages/typeorm/src/entity/comment.entity.ts
  packages/typeorm/src/entity/user.entity.ts
  packages/typeorm/src/entity/video.entity.ts
  packages/typeorm/src/migration/1573489846558-users.ts
  packages/typeorm/src/migration/1573489863767-videos.ts
  packages/typeorm/src/migration/1573521518584-add-relation-videos.ts
  packages/typeorm/src/migration/1573521657682-add-relation-comments.ts
  packages/typeorm/src/migration/1574410113562-add-videos-count-column-users.ts
  packages/typeorm/src/migration/1574415244805-alter-columns-videos.ts
  packages/typeorm/src/migration/1574418163970-alter-columnName-updateAt-videos.ts
  packages/typeorm/src/migration/1574418361009-alter-columnName-updateAt-tags.ts
  packages/typeorm/src/migration/1574418419310-alter-columnName-updateAt-comments.ts
Labels: refactor

#118 서버 프로젝트 절대 경로 사용 설정
  packages/server/package-lock.json
  packages/server/package.json
  packages/server/src/app.controller.ts
  packages/server/src/app.module.ts
  packages/server/src/authentication/authentication.controller.ts
  packages/server/src/authentication/authentication.module.ts
  packages/server/src/authentication/authentication.service.ts
  packages/server/src/authentication/model/session-jwt-data.ts
  packages/server/src/comment/comment.module.ts
  packages/server/src/comment/comment.service.ts
  packages/server/src/common/constants.ts
  packages/server/src/common/errors.ts
  packages/server/src/common/middlewares/deserializer/deserializer.middleware.ts
  packages/server/src/common/pipes/id-parser/id-parser.pipe.ts
  packages/server/src/libs/cookie-setter/index.ts
  packages/server/src/libs/custom-map/index.ts
  packages/server/src/libs/get-offset/index.ts
  packages/server/src/logger/index.ts
  packages/server/src/main.ts
  packages/server/src/serializer/user-serializer.module.ts
  packages/server/src/serializer/user-serializer.service.ts
  packages/server/src/third-party-api/github-api/github-api.module.ts
  packages/server/src/third-party-api/github-api/github-api.service.ts
  packages/server/src/third-party-api/model/github-user-detail.ts
  packages/server/src/uploaded-video-table/model/uploaded-video-info.ts
  packages/server/src/uploaded-video-table/uploaded-video-table.module.ts
  packages/server/src/uploaded-video-table/uploaded-video-table.service.ts
  packages/server/src/user-session/user-session.module.ts
  packages/server/src/user-session/user-session.service.ts
  packages/server/src/user/model/sign-up-form-data.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.module.ts
  packages/server/src/user/user.service.ts
  packages/server/src/video/dto/comment-response.dto.ts
  packages/server/src/video/dto/comments-response.dto.ts
  packages/server/src/video/dto/video-response.dto.ts
  packages/server/src/video/dto/videos-response.dto.ts
  packages/server/src/video/pipe/comments-param-pipe.ts
  packages/server/src/video/pipe/comments-query-pipe.ts
  packages/server/src/video/pipe/replies-param-pipe.ts
  packages/server/src/video/pipe/replies-query-pipe.ts
  packages/server/src/video/pipe/video-param-pipe.ts
  packages/server/src/video/pipe/videos-query-pipe.ts
  packages/server/src/video/video.controller.ts
  packages/server/src/video/video.module.ts
  packages/server/src/video/video.service.ts
  packages/server/src/webhook/transcoder/dto/elastic-transcoder/transcoder-notification.dto.ts
  packages/server/src/webhook/transcoder/transcoder-webhook.controller.ts
  packages/server/src/webhook/transcoder/transcoder-webhook.module.ts
  packages/server/src/webhook/webhook.module.ts
  packages/server/test/app.e2e-spec.ts
  packages/server/tsconfig.json
Labels: refactor

#121 클라이언트에서 로그인 여부 검사
  packages/client/.env.dummy
  packages/client/components/AppBar/index.tsx
  packages/client/components/AppBar/styles.tsx
  packages/client/components/UserProvider/contexts.ts
  packages/client/components/UserProvider/hooks.ts
  packages/client/components/UserProvider/index.tsx
  packages/client/components/VideoItem/index.tsx
  packages/client/constants.ts
  packages/client/package-lock.json
  packages/client/package.json
  packages/client/pages/_app.tsx
  packages/server/.env.dummy
  packages/server/src/authentication/authentication.controller.ts
  packages/server/src/authentication/authentication.service.ts
  packages/server/src/authentication/model/user-public-info.ts
  packages/server/src/common/constants.ts
  packages/server/src/libs/cookie-setter/index.ts
  packages/typeorm/src/entity/user.entity.ts
Labels: enhancement

#131 유저 상세 페이지 데이터 렌더링
  packages/client/components/AppBar/index.tsx
  packages/client/components/AppBar/styles.tsx
  packages/client/components/CircularLoader/index.tsx
  packages/client/components/CircularLoader/styles.tsx
  packages/client/components/GlobalStyles/index.ts
  packages/client/components/UserProfile/index.tsx
  packages/client/components/UserProfile/skeleton.tsx
  packages/client/components/UserProfile/styles.tsx
  packages/client/components/VideoComments/hooks.ts
  packages/client/components/VideoComments/index.tsx
  packages/client/components/VideoItem/index.tsx
  packages/client/components/VideoItem/skeleton.tsx
  packages/client/components/VideoItem/styles.tsx
  packages/client/constants.ts
  packages/client/svgs/PowerSVG/index.tsx
  packages/client/svgs/SettingsSVG/index.tsx
  packages/client/svgs/index.tsx
  packages/client/views/Hotlist/hooks.ts
  packages/client/views/Latest/hooks.ts
  packages/client/views/User/hooks.ts
  packages/client/views/User/index.tsx
  packages/client/views/User/styles.tsx
  packages/server/src/common/constants.ts
  packages/server/src/user/constants.ts
  packages/server/src/user/dto/user-param.dto.ts
  packages/server/src/user/dto/user-response.dto.ts
  packages/server/src/user/dto/user-video-list-param.dto.ts
  packages/server/src/user/dto/user-video-list-query.dto.ts
  packages/server/src/user/dto/user-video-list-response.dto.ts
  packages/server/src/user/dto/user-video-response.dto.ts
  packages/server/src/user/model/user-video-info.ts
  packages/server/src/user/pipe/user-param.pipe.ts
  packages/server/src/user/pipe/user-video-list-param.pipe.ts
  packages/server/src/user/pipe/user-video-list-query.pipe.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.module.ts
  packages/server/src/user/user.service.ts
  packages/server/src/video/pipe/comments-query-pipe.ts
  packages/server/src/video/video.service.ts
Labels: enhancement

#149 검색 API에대해 TEST 코드 구현
  packages/server/package.json
  packages/server/src/tag/dto/tag-list-query.dto.ts
  packages/server/src/tag/interface/QueryOptionWhere.ts
  packages/server/src/tag/tag.service.spec.ts
  packages/server/src/tag/tag.service.ts
  packages/server/src/tag/tag.test.dummy.data.ts
  packages/server/src/user/user.service.spec.ts
  packages/server/src/user/user.service.ts
  packages/server/src/user/user.test.dummy.data.ts
  packages/server/src/video/interface/QueryOptionWhere.ts
  packages/server/src/video/video.service.spec.ts
  packages/server/src/video/video.service.ts
  packages/server/src/video/video.test.dummy.data.ts
Labels: enhancement

#172 serverless framework 를 이용한 배포 코드 작성
  packages/client/.env.dummy
  packages/server/config/config.js
  packages/server/package-lock.json
  packages/server/package.json
  packages/server/serverless.yml
Labels: enhancement

#170 서버리스 배포 자동화 설정
  package-lock.json
  package.json
  packages/client/.gitignore
  packages/client/.serverless/Deploy.alexkwonisawesome.json
  packages/client/.serverless/Deploy.alexkwonisawesome.wedev-client.AwsS3.json
  packages/client/.serverless/Deploy.alexkwonisawesome.wedev-client.CloudFront.json
  packages/client/.serverless/Deploy.alexkwonisawesome.wedev-client.defaultEdgeLambda.AwsIamRole.json
  packages/client/.serverless/Deploy.alexkwonisawesome.wedev-client.defaultEdgeLambda.json
  packages/client/.serverless/Deploy.atercatus.json
  packages/client/.serverless/Deploy.atercatus.wedev-client.AwsS3.json
  packages/client/.serverless/Deploy.atercatus.wedev-client.CloudFront.json
  packages/client/.serverless/Deploy.atercatus.wedev-client.defaultEdgeLambda.AwsIamRole.json
  packages/client/.serverless/Deploy.atercatus.wedev-client.defaultEdgeLambda.json
  packages/client/.serverless/Deploy.kimjye.json
  packages/client/.serverless/Deploy.kimjye.wedev-client.AwsS3.json
  packages/client/.serverless/Deploy.kimjye.wedev-client.CloudFront.json
  packages/client/.serverless/Deploy.kimjye.wedev-client.defaultEdgeLambda.AwsIamRole.json
  packages/client/.serverless/Deploy.kimjye.wedev-client.defaultEdgeLambda.json
  packages/client/.serverless/Deploy.prod.json
  packages/client/.serverless/Deploy.prod.wedev-client.AwsS3.json
  packages/client/.serverless/Deploy.prod.wedev-client.CloudFront.json
  packages/client/.serverless/Deploy.prod.wedev-client.defaultEdgeLambda.AwsIamRole.json
  packages/client/.serverless/Deploy.prod.wedev-client.defaultEdgeLambda.json
  packages/client/.serverless/Deploy.riverandeye.json
  packages/client/.serverless/Deploy.riverandeye.wedev-client.AwsS3.json
  packages/client/.serverless/Deploy.riverandeye.wedev-client.CloudFront.json
  packages/client/.serverless/Deploy.riverandeye.wedev-client.defaultEdgeLambda.AwsIamRole.json
  packages/client/.serverless/Deploy.riverandeye.wedev-client.defaultEdgeLambda.json
  packages/client/.serverless/Deploy.stage.json
  packages/client/.serverless/Deploy.stage.wedev-client.AwsS3.json
  packages/client/.serverless/Deploy.stage.wedev-client.CloudFront.json
  packages/client/.serverless/Deploy.stage.wedev-client.defaultEdgeLambda.AwsIamRole.json
  packages/client/.serverless/Deploy.stage.wedev-client.defaultEdgeLambda.json
  packages/client/.serverless/_.json
  packages/client/env/.env.dummy
  packages/client/next.config.js
  packages/client/package-lock.json
  packages/client/package.json
  packages/client/serverless.js
  packages/client/serverless.yml
Labels: enhancement

#135 검색결과 화면 UI 및 라우팅
  packages/client/components/AppBar/index.tsx
  packages/client/components/SearchBar/index.tsx
  packages/client/components/SearchBar/style.tsx
  packages/client/components/SearchResultsProvider/context.ts
  packages/client/components/SearchResultsProvider/hook/use-searched-results.ts
  packages/client/components/SearchResultsProvider/index.tsx
  packages/client/components/SearchedResultsArea/index.tsx
  packages/client/components/SearchedResultsArea/style.tsx
  packages/client/components/SearchedResultsTitle/index.tsx
  packages/client/components/SearchedResultsTitle/style.tsx
  packages/client/components/ViewMore/index.tsx
  packages/client/components/ViewMore/style.tsx
  packages/client/constants.ts
  packages/client/pages/search/index.tsx
  packages/client/pages/search/tags/index.tsx
  packages/client/pages/search/users/index.tsx
  packages/client/pages/search/videos/index.tsx
  packages/client/svgs/ArrowRightSVG/index.tsx
  packages/client/svgs/SearchSVG/index.tsx
  packages/client/svgs/index.tsx
  packages/client/tslint.json
  packages/client/views/App/index.tsx
  packages/client/views/Search/index.tsx
  packages/client/views/Search/styles.tsx
  packages/client/views/SearchedResults/action/make-query-search-action.ts
  packages/client/views/SearchedResults/helper/filter-router.ts
  packages/client/views/SearchedResults/helper/make-custom-option-map.ts
  packages/client/views/SearchedResults/helper/make-custom-search-options.ts
  packages/client/views/SearchedResults/helper/make-option-map.ts
  packages/client/views/SearchedResults/helper/make-option-string.ts
  packages/client/views/SearchedResults/helper/set-option-map.ts
  packages/client/views/SearchedResults/hook/use-search-tags.ts
  packages/client/views/SearchedResults/hook/use-search-users.ts
  packages/client/views/SearchedResults/hook/use-search-videos.ts
  packages/client/views/SearchedResults/index.tsx
  packages/client/views/SearchedResults/style.tsx
  packages/client/views/SearchedResultsTags/index.tsx
  packages/client/views/SearchedResultsUsers/index.tsx
  packages/client/views/SearchedResultsVideos/index.tsx
Labels: enhancement

#148 로그인 페이지 및 회원가입 양식 페이지 구현
  packages/client/components/AppBar/index.tsx
  packages/client/components/AppBar/interface/index.ts
  packages/client/components/AppBar/styles.tsx
  packages/client/components/CommentItem/hooks.ts
  packages/client/constants.ts
  packages/client/env/.env.dummy
  packages/client/hooks/use-debounce.ts
  packages/client/libs/validation-state/validation-state.ts
  packages/client/views/Login/index.tsx
  packages/client/views/Login/styles.tsx
  packages/client/views/SignUp/action/make-query-user.ts
  packages/client/views/SignUp/action/make-sign-up-action.ts
  packages/client/views/SignUp/dto/sign-up-form-dto-factory.ts
  packages/client/views/SignUp/dto/sign-up-form-dto.ts
  packages/client/views/SignUp/helper/validate.ts
  packages/client/views/SignUp/helper/validation-state-factory.ts
  packages/client/views/SignUp/hook/use-sign-up.ts
  packages/client/views/SignUp/index.tsx
  packages/client/views/SignUp/model/duplication-check-states.ts
  packages/client/views/SignUp/model/form-data.ts
  packages/client/views/SignUp/model/user-form-state.ts
  packages/client/views/SignUp/model/user-form-validation-states.ts
  packages/client/views/SignUp/styles.tsx
  packages/server/package.json
  packages/server/src/common/pipes/id-parser/id-parser.pipe.ts
  packages/server/src/common/regexes.ts
  packages/server/src/user/model/duplicate-check-result.ts
  packages/server/src/user/pipe/user-name-param-pipe.ts
  packages/server/src/user/pipe/user-param.pipe.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.service.ts
  packages/server/src/video/video.service.ts
  packages/typeorm/src/migration/1574410113562-add-columns-users.ts
Labels: enhancement

#195 테스트코드 리팩토링 및 pipe 테스트코드 구현
  packages/client/.serverless/Deploy.kimjye.json
  packages/client/.serverless/Deploy.kimjye.wedev-client.CloudFront.json
  packages/client/.serverless/Deploy.kimjye.wedev-client.defaultEdgeLambda.AwsIamRole.json
  packages/client/.serverless/Deploy.kimjye.wedev-client.defaultEdgeLambda.json
  packages/client/serverless.js
  packages/server/src/tag/pipe/tag-list-query-pipe.spec.ts
  packages/server/src/tag/pipe/tag-list-query-pipe.ts
  packages/server/src/tag/tag.controller.ts
  packages/server/src/tag/tag.service.spec.ts
  packages/server/src/user/pipe/user-list-query-pipe.spec.ts
  packages/server/src/user/pipe/user-list-query-pipe.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.service.spec.ts
  packages/server/src/video/dto/video-list-query.dto.ts
  packages/server/src/video/pipe/video-list-query-pipe.spec.ts
  packages/server/src/video/pipe/video-list-query.pipe.ts
  packages/server/src/video/video.controller.ts
  packages/server/src/video/video.service.spec.ts
Labels: refactor

#210 배포 설정 추가
  packages/server/config/config.js
Labels: enhancement

#235 동영상 페이지 버그 수정 및 리팩토링
  packages/client/components/AppBar/index.tsx
  packages/client/components/CommentItem/index.tsx
  packages/client/components/CommentItem/style.tsx
  packages/client/components/VideoMeta/index.tsx
  packages/client/components/VideoMeta/styles.tsx
  packages/client/views/Tags/styles.tsx
  packages/client/views/Video/index.tsx
  packages/server/src/authentication/authentication.service.ts
  packages/server/src/video/video.controller.ts
Labels: bug

#234 비디오 리스트 버그 상황 해소
  packages/client/components/CommentItem/action/make-create-reply-action.ts
  packages/client/components/CommentItem/action/make-delete-comment-action.ts
  packages/client/components/CommentItem/action/make-edit-comment-action.ts
  packages/client/components/CommentItem/action/make-like-comment-action.ts
  packages/client/components/CommentItem/action/make-query-replies-action.ts
  packages/client/components/CommentItem/action/make-unlike-comment-action.ts
  packages/client/components/CommentItem/action/make-update-comment-action.ts
  packages/client/components/SearchedResultsArea/index.tsx
  packages/client/components/VideoComments/action/make-create-comment-action.ts
  packages/client/components/VideoComments/action/make-query-latest-comments-action.ts
  packages/client/components/VideoComments/action/make-query-popular-comments-action.ts
  packages/client/components/VideoComments/index.tsx
  packages/client/components/VideoInfo/action/make-like-video-action.ts
  packages/client/components/VideoInfo/action/make-unlike-video-action.ts
  packages/client/components/VideoItem/index.tsx
  packages/client/components/VideoItem/skeleton.tsx
  packages/client/components/VideoItem/styles.tsx
  packages/client/components/VideoListSkeleton/index.tsx
  packages/client/components/VideoUploadingModal/index.tsx
  packages/client/constants.ts
  packages/client/libs/parse-playtime/index.ts
  packages/client/libs/parsePlaytime.ts
  packages/client/views/Hotlist/action/make-query-hotlists.ts
  packages/client/views/Hotlist/hook/use-hotlist-videos.ts
  packages/client/views/Hotlist/hooks.ts
  packages/client/views/Hotlist/index.tsx
  packages/client/views/Latest/action/mutate-query-latest.ts
  packages/client/views/Latest/hook/use-latest-videos.ts
  packages/client/views/Latest/index.tsx
  packages/client/views/TagVideos/hook/use-tag-videos.ts
  packages/client/views/TagVideos/index.tsx
  packages/client/views/User/action/make-query-user-profile.ts
  packages/client/views/User/action/make-query-user-videos.ts
  packages/client/views/User/hook/use-user-profile.ts
  packages/client/views/User/hook/use-user-videos.ts
  packages/client/views/User/hooks.ts
  packages/client/views/User/index.tsx
  packages/client/views/User/styles.tsx
Labels: bug

#227 검색 결과 탭바 오류 수정
  packages/client/.serverless/Deploy.kimjye.wedev-client.CloudFront.json
  packages/client/.serverless/Deploy.kimjye.wedev-client.defaultEdgeLambda.json
  packages/client/components/SearchResultsProvider/helper/make-custom-option-map.ts
  packages/client/components/SearchResultsProvider/hook/use-searched-results.ts
  packages/client/components/SearchResultsProvider/index.tsx
  packages/client/constants.ts
  packages/client/package.json
  packages/client/views/SearchedResults/helper/filter-router.ts
  packages/client/views/SearchedResults/helper/make-custom-search-options.ts
  packages/client/views/SearchedResults/helper/make-option-map.ts
  packages/client/views/SearchedResults/helper/set-option-map.ts
  packages/client/views/SearchedResults/hook/use-search-tags.ts
  packages/client/views/SearchedResults/hook/use-search-users.ts
  packages/client/views/SearchedResults/hook/use-search-videos.ts
  packages/client/views/SearchedResults/index.tsx
  packages/client/views/SearchedResultsTags/index.tsx
  packages/client/views/SearchedResultsUsers/index.tsx
  packages/client/views/SearchedResultsVideos/index.tsx
  packages/server/package.json
Labels: bug
