Repository connect-foundation/2019-10, pull requests merged in 2019-11, with the labels that each got.

#44 Typeorm의 entity와 migration file 추가 및 수정
  packages/typeorm/src/entity/base.entity.ts
  packages/typeorm/src/entity/comment.entity.ts
  packages/typeorm/src/entity/tag.entity.ts
  packages/typeorm/src/entity/user.entity.ts
  packages/typeorm/src/entity/video.entity.ts
  packages/typeorm/src/migration/1573489846558-users.ts
  packages/typeorm/src/migration/1573489863767-videos.ts
  packages/typeorm/src/migration/1573489925976-tags.ts
  packages/typeorm/src/migration/1573489986529-tagged-videos.ts
  packages/typeorm/src/migration/1573490045118-comments.ts
  packages/typeorm/src/migration/1573490064876-replies.ts
  packages/typeorm/src/migration/1573521518584-add-columns-videos.ts
  packages/typeorm/src/migration/1573521605970-add-columns-tagged-videos.ts
  packages/typeorm/src/migration/1573521657682-add-columns-comments.ts
  packages/typeorm/src/migration/1573521757716-add-columns-replies.ts
  packages/typeorm/src/migration/1573739657863-liked-videos.ts
  packages/typeorm/src/migration/1573796390978-liked-comments.ts
Labels: enhancement

#47 Feature/login page ui 20191115
  packages/client/components/nav.js
  packages/client/pages/login.tsx
  packages/client/svgs/GitHubSVG/index.tsx
  packages/client/svgs/LogoSVG/index.tsx
  packages/client/views/Login/index.tsx
  packages/client/views/Login/styles.tsx
Labels: enhancement

#48 Feature/tag list page 20191116
  packages/client/.babelrc
  packages/client/components/AppBar/index.tsx
  packages/client/components/Drawer/index.tsx
  packages/client/components/GlobalStyles/index.ts
  packages/client/constants.ts
  packages/client/pages/_document.tsx
  packages/client/pages/tags/index.tsx
  packages/client/static/fonts/NanumSquareB.eot
  packages/client/static/fonts/NanumSquareB.ttf
  packages/client/static/fonts/NanumSquareB.woff
  packages/client/static/fonts/NanumSquareEB.eot
  packages/client/static/fonts/NanumSquareEB.ttf
  packages/client/static/fonts/NanumSquareEB.woff
  packages/client/static/fonts/NanumSquareR.eot
  packages/client/static/fonts/NanumSquareR.ttf
  packages/client/static/fonts/NanumSquareR.woff
  packages/client/static/fonts/styles.css
  packages/client/views/TagList/index.tsx
  packages/client/views/TagList/styles.tsx
Labels: enhancement

#52 comment entity 에 ManyToMany 관계 변수 타입 수정
  packages/typeorm/src/entity/base.entity.ts
  packages/typeorm/src/entity/comment.entity.ts
  packages/typeorm/src/entity/video.entity.ts
  packages/typeorm/src/migration/1573489846558-users.ts
  packages/typeorm/src/migration/1573489863767-videos.ts
  packages/typeorm/src/migration/1573489925976-tags.ts
  packages/typeorm/src/migration/1573489986529-tagged-videos.ts
  packages/typeorm/src/migration/1573490045118-comments.ts
  packages/typeorm/src/migration/1573521518584-add-columns-videos.ts
  packages/typeorm/src/migration/1573521657682-add-columns-comments.ts
  packages/typeorm/src/migration/1573739657863-liked-videos.ts
  packages/typeorm/src/migration/1573796390978-liked-comments.ts
Labels: bug

#58 영상 리스트 화면 구성 및 스타일 조정
  packages/client/components/AppBar/index.tsx
  packages/client/components/AppBar/styles.tsx
  packages/client/components/CommentForm/styles.tsx
  packages/client/components/CommentItem/styles.tsx
  packages/client/components/Content/styles.tsx
  packages/client/components/Drawer/index.tsx
  packages/client/components/Drawer/styles.tsx
  packages/client/components/Filters/styles.tsx
  packages/client/components/Layout/index.tsx
  packages/client/components/Video/index.tsx
  packages/client/components/VideoInfo/styles.tsx
  packages/client/components/VideoItem/index.tsx
  packages/client/components/VideoItem/styles.tsx
  packages/client/components/VideoMeta/styles.tsx
  packages/client/constants.ts
  packages/client/pages/index.tsx
  packages/client/pages/latest.tsx
  packages/client/svgs/HotlistSVG/index.tsx
  packages/client/svgs/LatestSVG/index.tsx
  packages/client/svgs/LogoSVG/index.tsx
  packages/client/svgs/TagsSVG/index.tsx
  packages/client/svgs/TopicsSVG/index.tsx
  packages/client/svgs/index.tsx
  packages/client/views/Hotlist/index.tsx
  packages/client/views/Hotlist/styles.tsx
  packages/client/views/Latest/index.tsx
  packages/client/views/Latest/styles.tsx
  packages/client/views/Main/index.tsx
  packages/client/views/TagList/styles.tsx
  packages/client/views/Video/styles.tsx
Labels: enhancement

#64 AppBar 부분 검색 UI 및 라우팅
  packages/client/components/AppBar/index.tsx
  packages/client/components/AppBar/styles.tsx
  packages/client/components/GlobalStyles/index.ts
  packages/client/components/SearchBar/index.tsx
  packages/client/components/SearchBar/styles.tsx
  packages/client/pages/search/index.tsx
  packages/client/svgs/ArrowBackSVG/index.tsx
  packages/client/svgs/SearchSVG/index.tsx
  packages/client/svgs/index.tsx
  packages/client/views/Search/index.tsx
  packages/client/views/Search/styles.tsx
Labels: enhancement

#68 유저 페이지 마크업 및 스타일 작성
  packages/client/components/AppBar/styles.tsx
  packages/client/components/UserProfile/index.tsx
  packages/client/components/UserProfile/styles.tsx
  packages/client/components/VideoItem/index.tsx
  packages/client/components/VideoItem/styles.tsx
  packages/client/libs/videoList.ts
  packages/client/pages/users/[userId].tsx
  packages/client/svgs/LogoSVG/index.tsx
  packages/client/views/Hotlist/styles.tsx
  packages/client/views/User/index.tsx
  packages/client/views/User/styles.tsx
Labels: enhancement

#78 [database] | feat(entity): 각 table내 count 및 popularity 컬럼 추가
  packages/typeorm/src/entity/comment.entity.ts
  packages/typeorm/src/entity/tag.entity.ts
  packages/typeorm/src/entity/user.entity.ts
  packages/typeorm/src/entity/video.entity.ts
Labels: refactor

#80 Database Migration 변경
  packages/typeorm/src/migration/1574410113562-add-videosCount-column-users.ts
  packages/typeorm/src/migration/1574415244805-alter-columns-videos.ts
  packages/typeorm/src/migration/1574416436192-add-columns-videos.ts
  packages/typeorm/src/migration/1574417109077-add-columns-comments.ts
  packages/typeorm/src/migration/1574417456173-add-column-tags.ts
  packages/typeorm/src/migration/1574418163970-alter-columnName-updateAt-videos.ts
  packages/typeorm/src/migration/1574418361009-alter-columnName-updateAt-tags.ts
  packages/typeorm/src/migration/1574418419310-alter-columnName-updateAt-comments.ts
Labels: enhancement

#90 비디오 리스트 관련 기능 추가
  packages/client/components/AppBar/index.tsx
  packages/client/components/AppBar/styles.tsx
  packages/client/components/CircularProgress/index.tsx
  packages/client/components/CircularProgress/styles.tsx
  packages/client/components/Filters/index.tsx
  packages/client/components/Layout/index.tsx
  packages/client/components/SearchBar/index.tsx
  packages/client/components/SearchBar/styles.tsx
  packages/client/components/VideoItem/index.tsx
  packages/client/components/VideoItem/styles.tsx
  packages/client/constants.ts
  packages/client/libs/fetching/cache.ts
  packages/client/libs/fetching/client.ts
  packages/client/libs/fetching/index.ts
  packages/client/libs/parsePlaytime.ts
  packages/client/libs/timeago.ts
  packages/client/package-lock.json
  packages/client/package.json
  packages/client/pages/_app.tsx
  packages/client/svgs/SearchSVG/index.tsx
  packages/client/views/Hotlist/hooks.ts
  packages/client/views/Hotlist/index.tsx
  packages/client/views/Hotlist/styles.tsx
  packages/client/views/Latest/hooks.ts
  packages/client/views/Latest/index.tsx
  packages/client/views/Latest/styles.tsx
  packages/server/.env.dummy
  packages/server/package-lock.json
  packages/server/package.json
  packages/server/src/common/pipes/get-videos.pipe/dto.ts
  packages/server/src/common/pipes/get-videos.pipe/index.ts
  packages/server/src/main.ts
  packages/server/src/video/constants.ts
  packages/server/src/video/dto/index.ts
  packages/server/src/video/dto/video-response.dto.ts
  packages/server/src/video/dto/video-user.dto.ts
  packages/server/src/video/dto/videos-query.dto.ts
  packages/server/src/video/video.controller.ts
  packages/server/src/video/video.service.ts
  packages/typeorm/src/entity/comment.entity.ts
  packages/typeorm/src/entity/video.entity.ts
Labels: enhancement

#94 PR Review 에서 발생한 CL 적용입니다.
  packages/client/pages/videos/upload.tsx
  packages/client/views/Upload/dto/upload-video.dto.ts
  packages/client/views/Upload/index.tsx
  packages/client/views/Upload/styles.tsx
  packages/client/views/Video/Upload/index.tsx
  packages/lambda/encode-video/.env.dummy
  packages/lambda/encode-video/index.js
  packages/lambda/presigned-url/.env.dummy
  packages/server/.env.dummy
  packages/server/src/main.ts
  packages/server/src/webhook/transcoder/transcoder-webhook.controller.ts
Labels: refactor
